### PR TITLE
Allow the worker to access the web instance

### PR DESCRIPTION
**Pull request by steveYeah**
Add the NAT IP to grant it access on ports 80, 443, 3000, 8844, 8443

This is related to issue https://github.com/EngineerBetter/concourse-up/issues/53

### CODE REVIEW

**Comment by steveYeah** [comment]
@DanielJonesEB @crsimmons @takeyourhatoff @peterellisjones Just a little nudge on this. Thanks!

**Comment by steveYeah** [comment]
Thanks @crsimmons, I'll take a look and shout if there are any problems 👍

**Comment by crsimmons** [comment]
@steveYeah (cc @archgrove).

Due to some refactoring we had to implement this change ourselves. This is now implemented in [the latest release](https://github.com/EngineerBetter/concourse-up/releases/tag/0.11.0).

As a consequence I'm closing this PR now. Thanks for helping us identify this change!

**Comment by steveYeah** [comment]
@crsimmons No worries 👍 Glad it helped

**Pull request closed without merging**
